name: Basic Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        version:
          - v0.0.1-riker.1
          - 1.0.0-beta.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare release
        uses: ./
        with:
          version: ${{ matrix.version }}
          commands: |
            echo "hello there"
            pwd

