name: Basic Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        version:
          - v0.0.1-riker.1
          - 1.0.0-beta.1
        node-version:
          - '16'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install deps and prep
        run: |
          npm ci
          npm run prepare
          npm run lint

      - name: Prepare release
        uses: ./
        with:
          version: ${{ matrix.version }}
          sync: false
          commands: |
            echo "hello there"
            pwd

