name: Test Inputs

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare release
        uses: ./
